<?php $_product = $this->getProduct(); ?>
<a class="popup-link-1" href="">Request Price</a>
<div class="popup-box" id="popup-box-1">
    <div class="close">X</div>
    <div class="top">
        <div class="page-title">
            <h3 ><?php echo Mage::helper('task')->__('Request Price') ?></h3>
        </div>
    </div>
    <div class="bottom">
        <form id="requestForm" action="" method="post" class="scaffold-form">
            <div class="fieldset">
                <h2 class="legend"><?php echo Mage::helper('task')->__('Request Information') ?></h2>
                <p class="required"><?php echo Mage::helper('task')->__('* Required Fields') ?></p>
                <ul class="form-list">
                    <li class="fields">
                        <div class="field">
                            <label for="name" class="required"><em>*</em><?php echo Mage::helper('task')->__('Name') ?></label>
                            <div class="input-box">
                                <input name="name" id="name" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('task')->__('Name')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                            </div>
                        </div>
                        <div class="field">
                            <label for="email" class="required"><em>*</em><?php echo Mage::helper('task')->__('Email') ?></label>
                            <div class="input-box">
                                <input name="email" id="email" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('task')->__('Email')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="email" autocapitalize="off" autocorrect="off" spellcheck="false" />
                            </div>
                        </div>
                    </li>
                    <li class="wide">
                        <label for="comment" class="required"><em>*</em><?php echo Mage::helper('task')->__('Comment') ?></label>
                        <div class="input-box">
                            <textarea name="created_at" id="comment" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Comment')) ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="buttons-set">
                <input type="hidden" value="<?php echo $this->htmlEscape($_product->getData('sku')); ?>" name="product_sku" title="<?php echo Mage::helper('task')->__('Sku') ?>"/>
                <button type="submit" name="submit" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('task')->__('Submit')) ?>" class="button"><span><span><?php echo Mage::helper('task')->__('Submit') ?></span></span></button>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    var postUrl = "<?php echo $this->getUrl('task/index/saveform'); ?>";

    (function ($j) {
        $j(document).ready(function(){
            $j("#requestForm").submit(function() {
                var form_data = $j(this).serialize();
                $j.ajax({
                    type: "POST",
                    url: postUrl,
                    data: form_data,
                    success: function(data) {

                        console.log(data);
                    },
                    error: function( xhr, textStatus ) {
                        alert( [ xhr.status, textStatus ] );
                    }
                });
            });
        });
    }) ($j);
   //]]>
</script>